### ISSUE TITLE
suggestion: Add support for chaining 'addCrumb' method.

### ISSUE THREAD

**Issue by nelson6e65** [creitive/breadcrumbs#17]
:one: It should be nice if we can chain methods like:

```php
<?php
$breadcrumbs->addCrumb('Home', '/')
    ->addCrumb('Pages', 'pages')
    ->addCrumb('Subpage', 'subpage')
    ->addCrumb('Subsubpage', '/subsubpage')
    ->addCrumb('Other website', 'http://otherwebsite.com/some-page');
?>
```

I think is not hard to implement, it just need return `$this` in  `addCrumb` method.

:two: And, maybe, refactorize  `addCrumb` name to `add` (shortest name) or add it as an alias:

```php
<?php
$breadcrumbs->add('Home', '/')
    ->add('Pages', 'pages')
    ->add('Subpage', 'subpage')
    ->add('Subsubpage', '/subsubpage')
    ->add('Other website', 'http://otherwebsite.com/some-page');
?>
```

**Comment by levacic** [comment]
I like both suggestions, and regarding BC breaks:

- The first suggestions should be okay, as I can't think of an example where someone relies on a method not returning anything
- As for the second one, renaming is not an option, but an alias is okay

Would you like to submit a PR?

**Comment by nelson6e65** [comment]
Yes, obvious you can't remove `addCrumb` method directly, I meant deprecate to next major version to be replaced by `add`, but an alias it's enough. :smile: 

About the pull request, I'm busy right now in my job. In order to add tests and etc, I would need some time that I have not right now (I'm using only my job's PC). :disappointed: 

But in the weekend I will get my own PC repaired, and I will not have any problem to do it. :+1:

**Comment by levacic** [comment]
Great, looking forward to it, thank!
