### ISSUE TITLE
List Item Classes and Bootstrap 4

### ISSUE THREAD

**Issue by bcorcoran** [creitive/breadcrumbs#20]
Hi,

There is currently no way to configure classes for list items generated breadcrumbs. I don't think a PR is needed, but if your goal is to support bootstrap or other css frameworks, it might be helpful to add a `setListItemClass` method similar to `setCssClasses` so that you can add default classes to the actual list breadcrumb `li`'s.

For example, bootstrap 4 uses the following markup:

```
<ol class="breadcrumb">
  <li class="breadcrumb-item"><a href="#">Home</a></li>
  <li class="breadcrumb-item"><a href="#">Library</a></li>
  <li class="breadcrumb-item active">Data</li>
</ol>
```

Currently, the only class that is added to `li`'s is `active`. I've manually added `breadcrumb-item` in my copy of this, but I think others would appreciate this as an option.

**Comment by levacic** [comment]
That makes complete sense, sorry for the wait. Added a `setListItemCssClass()` method.
