### ISSUE TITLE
"Best Practices" for using this add on?

### ISSUE THREAD

**Issue by SaintPeter** [creitive/breadcrumbs#6]
It would be helpful to show some simple "Best Practices" for using this plugin.  I think I understand, in general, how it works, but it would be nice to see where the obvious places to put the components are.  At least, it's not obvious to me where to put them.

I'm looking for where to place them to minimize duplication of code and simplify build-out.

**Comment by sbourdette** [comment]
Sorry, but I can't understand how a controller can extend BaseController since it extends already Controller Class.
It could be great to provide an sample of Controller.

**Comment by levacic** [comment]
@sbourdette Just have some kind of an `App\BaseController` in your app that extends your framework's `Framework\Controller` class, and then make all other controller classes within the app extend `App\BaseController` instead of `Framework\Controller`. Does that make sense?

**Comment by sbourdette** [comment]
Ok it's clear for me.
Thanks @levacic
